# Generated by Django 3.0.6 on 2020-05-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myusers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='status',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
