# Generated by Django 3.0.6 on 2020-05-25 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=100)),
                ('prescription', models.CharField(max_length=250)),
                ('doctor', models.IntegerField()),
                ('patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.MyUsers')),
            ],
        ),
    ]
